import { Database } from "@/lib/definitions/database.types";

// 1. Extract the base Row type generated by Supabase
export type SourceValidation =
  Database["public"]["Tables"]["source_validations"]["Row"];

// 2. Map the boolean states to strict constants for UI and logic use
export const SOURCE_VALIDATION_STATE = {
  VALIDATED: true, // ArrowBigUp
  REFUTED: false, // ArrowBigDown
} as const;

// 3. Create a union type of the possible values (boolean)
export type SourceValidationState =
  (typeof SOURCE_VALIDATION_STATE)[keyof typeof SOURCE_VALIDATION_STATE];
